UNIVARIATE_DATASET_NAMES = [
    # "ACSF1",
    "Adiac",
    # "AllGestureWiimoteX",
    # "AllGestureWiimoteY",
    # "AllGestureWiimoteZ",
    "ArrowHead",
    # "Beef",
    "BeetleFly",
    # "BirdChicken",
    # "BME",
    # "Car",
    # "CBF",
    # "Chinatown",
    # "ChlorineConcentration",
    # "CinCECGTorso",
    # "Coffee",
    # "Computers",
    # "CricketX",
    # "CricketY",
    # "CricketZ",
    # "Crop",
    # "DiatomSizeReduction",
    # "DistalPhalanxOutlineAgeGroup",
    # "DistalPhalanxOutlineCorrect",
    # "DistalPhalanxTW",
    # "DodgerLoopDay",
    # "DodgerLoopGame",
    # "DodgerLoopWeekend",
    # "Earthquakes",
    "ECG200",
    # "ECG5000",
    # "ECGFiveDays",
    # "ElectricDevices",
    # "EOGHorizontalSignal",
    # "EOGVerticalSignal",
    # "EthanolLevel",
    # "FaceAll",
    # "FaceFour",
    # "FacesUCR",
    # "FiftyWords",
    # "Fish",
    "FordA",
    # "FordB",
    # "FreezerRegularTrain",
    # "FreezerSmallTrain",
    # "Fungi",
    # "GestureMidAirD1",
    # "GestureMidAirD2",
    # "GestureMidAirD3",
    # "GesturePebbleZ1",
    # "GesturePebbleZ2",
    # "GunPoint",
    # "GunPointAgeSpan",
    # "GunPointMaleVersusFemale",
    # "GunPointOldVersusYoung",
    # "Ham",
    "HandOutlines",
    # "Haptics",
    # "Herring",
    # "HouseTwenty",
    # "InlineSkate",
    # "InsectEPGRegularTrain",
    # "InsectEPGSmallTrain",
    # "InsectWingbeatSound",
    # "ItalyPowerDemand",
    # "LargeKitchenAppliances",
    # "Lightning2",
    # "Lightning7",
    # "Mallat",
    # "Meat",
    # "MedicalImages",
    # "MelbournePedestrian",
    # "MiddlePhalanxOutlineAgeGroup",
    # "MiddlePhalanxOutlineCorrect",
    # "MiddlePhalanxTW",
    # "MixedShapesRegularTrain",
    # "MixedShapesSmallTrain",
    # "MoteStrain",
    "NonInvasiveFetalECGThorax1",
    # "NonInvasiveFetalECGThorax2",
    # "OliveOil",
    # "OSULeaf",
    # "PhalangesOutlinesCorrect",
    # "Phoneme",
    # "PickupGestureWiimoteZ",
    # "PigAirwayPressure",
    # "PigArtPressure",
    # "PigCVP",
    # "PLAID",
    # "Plane",
    # "PowerCons",
    # "ProximalPhalanxOutlineAgeGroup",
    # "ProximalPhalanxOutlineCorrect",
    # "ProximalPhalanxTW",
    # "RefrigerationDevices",
    # "Rock",
    # "ScreenType",
    # "SemgHandGenderCh2",
    # "SemgHandMovementCh2",
    # "SemgHandSubjectCh2",
    # "ShakeGestureWiimoteZ",
    # "ShapeletSim",
    "ShapesAll",
    # "SmallKitchenAppliances",
    # "SmoothSubspace",
    # "SonyAIBORobotSurface1",
    # "SonyAIBORobotSurface2",
    # "StarLightCurves",
    # "Strawberry",
    # "SwedishLeaf",
    # "Symbols",
    # "SyntheticControl",
    # "ToeSegmentation1",
    # "ToeSegmentation2",
    # "Trace",
    # "TwoLeadECG",
    # "TwoPatterns",
    # "UMD",
    # "UWaveGestureLibraryAll",
    # "UWaveGestureLibraryX",
    # "UWaveGestureLibraryY",
    # "UWaveGestureLibraryZ",
    # "Wafer",
    # "Wine",
    # "WordSynonyms",
    # "Worms",
    # "WormsTwoClass",
    # "Yoga",
]

ITERATIONS = 10  # nb of random runs for random initializations

UNIVARIATE_ARCHIVE_NAMES = ["TSC"]

CLASSIFIERS = ["fcn", "resnet", "encoder", "inception", "nne"]

# CLASSIFIERS = ['fcn','mlp','resnet','encoder','mcdcnn','cnn','nne','ensembletransfer']

# CLASSIFIERS = ['nne/mlp-','nne/fcn-','nne/resnet-','nne/encoder-','nne/mcdcnn-','nne/cnn-',
# 'nne/fcn-resnet-encoder-','ensembletransfer/NN(10)-weight(True)','ensembletransfer/NN(84)-weight(True)',
# 'ensembletransfer/NN(10)-weight(False)','ensembletransfer/NN(84)-weight(False)']
# CLASSIFIERS = ['ensembletransfer']
